name: "Adicionar not칤cia 游닗"
description: Adicione uma not칤cia ao app.
body:
- type: markdown
  attributes:
    value: |
      ## Adicione uma not칤cia ao site
      Preencha os campos abaixo para adicionar uma not칤cia ao site.
- type: input
  id: author
  attributes:
    label: author
    description: Autor da not칤cia
    placeholder: Autor da not칤cia

- type: input
  id: reference
  attributes:
    label: link
    description: Inclue o link da not칤cia.
    placeholder: www.astronomos.com.br

- type: input
  id: thumbnail
  attributes:
    label: thumbnail
    description: Insira o link da imagem de capa da not칤cia.
    placeholder: www.astronomos.com.br/imagem.jpg
- type: markdown
  attributes:
    value: |
      ### As not칤cias podem ter at칠 5 p치ginas no m치ximo. Preencha da melhor forma para que possamos publicar.
- type: markdown
  attributes:
    value: |
      ## P치gina 1
- type: textarea
  id: page1
  attributes:
    label: pagina_1
    description: Conte칰do da p치gina 1
    placeholder: Conte칰do da p치gina 1
- type: markdown
  attributes:
    value: |
      ## P치gina 2
- type: textarea
  id: page2
  attributes:
    label: pagina_2
    description: Conte칰do da p치gina 2
    placeholder: Conte칰do da p치gina 2
- type: markdown
  attributes:
    value: |
      ## P치gina 3

- type: textarea
  id: page3
  attributes:
    label: pagina_3
    description: Conte칰do da p치gina 1
    placeholder: Conte칰do da p치gina 1
- type: markdown
  attributes:
    value: |
      ## P치gina 4
- type: textarea
  id: page4
  attributes:
    label: pagina_4
    description: Conte칰do da p치gina 4
    placeholder: Conte칰do da p치gina 4
- type: markdown
  attributes:
    value: |
      ## P치gina 5
- type: textarea
  id: page5
  attributes:
    label: pagina_5
    description: Conte칰do da p치gina 5
    placeholder: Conte칰do da p치gina 5
labels: ["news"]
