name: New Action Test

on:
    pull_request:
        types: [labeled]
jobs:
  create-test-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Get Label
        id: get-label
        run: |
            PR_LABEL=$(jq --raw-output .label.name $GITHUB_EVENT_PATH)
            echo "Captured PR Label: $PR_LABEL"
            echo "::set-output name=pr_label::$PR_LABEL"

       # Trigger another workflow using the GitHub API
      - name: Trigger Workflow with Label
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         curl -X POST https://api.github.com/repos/caioProgramming/cosmosApp/actions/workflows/other-workflow.yml/dispatches \
         -H "Accept: application/vnd.github.v3+json" \
         -H "Authorization: token $GITHUB_TOKEN" \
         --data '{"ref":""}'


