name: New Action Test

on:
    pull_request:
        types: [opened]
jobs:
  create-test-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Check Branch
        id: check-branch
        run: |    
          PR_BRANCH=$(jq --raw-output .pull_request.head.ref $GITHUB_EVENT_PATH)
          echo "PR_BRANCH=$PR_BRANCH"
          if [[ "$PR_BRANCH" == *"git-action"* ]]; then
            echo "::set-output name=should_run::true"
          else
            echo "::set-output name=should_run::false"
          fi
        shell: bash
      - name: Create Test Branch
        run: |
          PR_BRANCH=$(jq --raw-output .pull_request.head.ref $GITHUB_EVENT_PATH)
          TEST_BRANCH="test/${PR_BRANCH}"
          git checkout -b $TEST_BRANCH
          git push origin $TEST_BRANCH

      - name: Trigger Another Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-test-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
